import { Company, CompanyData, LaborContract } from '../types/contract';
import { getDefaultLopcymatData } from './lopcymatData';
import { CURRENT_DEFAULT_BCV_RATE, LEGAL_CESTATICKET_USD } from './lotttCalculations';

export const DEFAULT_COMPANIES: Company[] = [
  {
    id: 'empresa-001',
    denominacionSocial: 'Inversiones & Manufacturas Venezolanas, C.A.',
    alias: 'Manufacturas VE',
    rif: 'J-31298450-4',
    registroMercantil: 'Registro Mercantil Segundo del Dtto. Capital y Edo. Miranda, Tomo 182-A, Número 45',
    domicilioFiscal: 'Avenida Francisco de Miranda, Torre Cavendes, Piso 9, Oficina 902, Los Palos Grandes, Chacao, Estado Miranda, Venezuela',
    representanteNombre: 'Alejandro Morales Mendoza',
    representanteCI: 'V-11.234.890',
    representanteCargo: 'Presidente Ejecutivo',
    representanteFacultad: 'conforme a facultades estatutarias de representación general inscritas en el Registro Mercantil',
    rnetNumero: 'RNET-VE-2024-99182',
    ivssPatronal: 'D-998811223',
    incesNumero: 'INC-445566',
    banavihNumero: 'BAN-112233',
    actividadEconomica: 'Manufactura Industrial, Metalmecánica y Comercialización',
    colorTheme: 'blue',
    fechaRegistro: '2023-01-15',
    activo: true
  },
  {
    id: 'empresa-002',
    denominacionSocial: 'Servicios Automotrices & Taller El Cauchero, C.A.',
    alias: 'Taller El Cauchero',
    rif: 'J-40981234-8',
    registroMercantil: 'Registro Mercantil Primero de la Circunscripción Judicial del Edo. Miranda, Tomo 94-B, N° 12',
    domicilioFiscal: 'Zona Industrial Los Ruices, Calle Milán con Av. Principal, Galpón N° 4, Municipio Sucre, Estado Miranda, Venezuela',
    representanteNombre: 'Gustavo Adolfo Benítez Silva',
    representanteCI: 'V-13.890.124',
    representanteCargo: 'Director Gerente',
    representanteFacultad: 'con amplias facultades de administración laboral y contractual según estatutos',
    rnetNumero: 'RNET-VE-2024-51029',
    ivssPatronal: 'A-774411002',
    incesNumero: 'INC-991122',
    banavihNumero: 'BAN-334455',
    actividadEconomica: 'Taller Mecánico, Montaje de Neumáticos, Balanceo y Servicios Automotrices',
    colorTheme: 'amber',
    fechaRegistro: '2023-06-20',
    activo: true
  },
  {
    id: 'empresa-003',
    denominacionSocial: 'Distribuidora & Logística Alimentos Caracas, C.A.',
    alias: 'Distribuidora Caracas',
    rif: 'J-50123891-0',
    registroMercantil: 'Registro Mercantil Cuarto del Distrito Capital, Tomo 210-C, Número 78',
    domicilioFiscal: 'Avenida Intercomunal de Antímano, Complejo Logístico La Yaguara, Nave 3, Caracas, Venezuela',
    representanteNombre: 'Mariana Elena Quintero Gómez',
    representanteCI: 'V-15.670.345',
    representanteCargo: 'Vicepresidenta de Operaciones',
    representanteFacultad: 'según poder general notariado debidamente facultado para contrataciones',
    rnetNumero: 'RNET-VE-2024-88419',
    ivssPatronal: 'B-332211990',
    incesNumero: 'INC-778899',
    banavihNumero: 'BAN-667788',
    actividadEconomica: 'Almacenamiento, Distribución y Ventas Masivas de Alimentos',
    colorTheme: 'emerald',
    fechaRegistro: '2023-09-10',
    activo: true
  },
  {
    id: 'empresa-004',
    denominacionSocial: 'Corporación Médica & Salud Ocupacional Integral, C.A.',
    alias: 'Salud Ocupacional Integral',
    rif: 'J-30495812-7',
    registroMercantil: 'Registro Mercantil Tercero del Distrito Capital y Estado Miranda, Tomo 112-A, Número 33',
    domicilioFiscal: 'Calle California con Av. Jalisco, Edificio Centro Quirúrgico Las Mercedes, Piso 4, Caracas, Venezuela',
    representanteNombre: 'Dr. Roberto José Vallenilla Ramos',
    representanteCI: 'V-10.982.456',
    representanteCargo: 'Director Médico y Laboral',
    representanteFacultad: 'según documento constitutivo estatutario',
    rnetNumero: 'RNET-VE-2024-12903',
    ivssPatronal: 'C-556677889',
    incesNumero: 'INC-223344',
    banavihNumero: 'BAN-889900',
    actividadEconomica: 'Servicios de Medicina Ocupacional, SST LOPCYMAT y Asesoría Laboral',
    colorTheme: 'purple',
    fechaRegistro: '2024-02-01',
    activo: true
  }
];

export const DEFAULT_COMPANY: CompanyData = DEFAULT_COMPANIES[0];

export const INITIAL_CONTRACTS: LaborContract[] = [
  {
    id: 'contract-001',
    codigoExpediente: 'NOM-2026-0001',
    fechaCreacion: '2026-01-15',
    fechaInicioRelacion: '2026-01-15',
    modalidad: 'indeterminado',
    cargo: 'Gerente de Administración y Finanzas',
    clasificacion: 'direccion',
    descripcionFunciones: 'Dirección, supervisión y formulación de planes financieros corporativos, auditorías internas, relación con entidades bancarias y tributarias (SENIAT), elaboración de presupuestos anuales y liderazgo del equipo contable de la empresa.',
    lugarPrestacion: 'Sede Principal Corporativa - Torre Cavendes, Chacao, Edo. Miranda',
    domicilioEspecialConvenido: 'Caracas, Circunscripción Judicial del Área Metropolitana de Caracas',
    tipoJornada: 'Exenta_Direccion',
    horasSemanales: 40,
    horarioDetallado: 'Sin sujeción a horario fijo por aplicación del Artículo 178 LOTTT (Personal de Dirección)',
    diasDescanso: 'Sábados y Domingos continuos',
    empresaId: 'empresa-001',
    empresa: DEFAULT_COMPANIES[0],
    trabajador: {
      nombres: 'Valeria Sofía',
      apellidos: 'Rivas Salazar',
      cedula: 'V-16.789.412',
      nacionalidad: 'Venezolana',
      edad: 38,
      estadoCivil: 'Casado(a)',
      profesionOficio: 'Licenciada en Contaduría Pública y Especialista en Finanzas',
      direccionHabitacion: 'Urb. Santa Mónica, Calle Teresa de la Parra, Edif. Ávila, Apto 5-B, Municipio Libertador, Caracas',
      telefono: '+58 414-2391082',
      correo: 'valeria.rivas@manufacturasve.com'
    },
    remuneracion: {
      tipoMoneda: 'USD_INDEXADO',
      salarioBaseMensualUSD: 1400,
      salarioBaseMensualVEF: 1400 * CURRENT_DEFAULT_BCV_RATE,
      tasaBCV: CURRENT_DEFAULT_BCV_RATE,
      fechaTasaBCV: '2026-10-05',
      periodicidadPago: 'Quincenal',
      diaPago: 'los días 15 y último de cada mes',
      lugarPago: 'transferencia electrónica en cuenta nómina bancaria autorizada',
      cestaticketUSD: LEGAL_CESTATICKET_USD,
      cestaticketVEF: LEGAL_CESTATICKET_USD * CURRENT_DEFAULT_BCV_RATE,
      esquemaMixto: false,
      diasBonoVacacional: 20,
      diasUtilidades: 60,
      bonosNoSalarialesDeclarados: 0,
      alertaRiesgoSalarizacion: false
    },
    aplicaConvencionColectiva: false,
    incluyePeriodoPrueba: false,
    lopcymat: {
      ...getDefaultLopcymatData('direccion'),
      horasCapacitacionTrimestralesCompletadas: 16
    },
    dobleEjemplarEmitido: true,
    constanciaEntregaFirmada: true,
    status: 'firmado_ambos',
    numeroProrroga: 0,
    auditTrail: {
      auditId: 'AUD-88F91A01',
      timestampUtc: '2026-01-15T14:30:00.000Z',
      timestampLocal: '15/01/2026, 10:30:00 a. m.',
      signerIdentityHash: 'b4a6f7e8c9d0123456789abcdef0123456789abcdef0123456789abcdef01234',
      signerName: 'Valeria Sofía Rivas Salazar',
      signerCedula: 'V-16.789.412',
      signerEmail: 'valeria.rivas@manufacturasve.com',
      signerPhone: '+58 414-2391082',
      signatureLevel: 'nivel_3',
      signatureLevelName: 'Nivel 3 - Calificada Avanzada (OTP + Hash SHA-256 + Geotrazabilidad)',
      sha256DocumentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      deviceFingerprint: 'VE-WEB-CHROME-M1-098172',
      ipAddress: '190.202.74.88',
      geolocationLatLong: '10.4960° N, 66.8525° W (Chacao, Miranda)',
      otpChannelDelivery: 'WHATSAPP',
      otpCodeHash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b'
    }
  },
  {
    id: 'contract-002',
    codigoExpediente: 'NOM-2026-0002',
    fechaCreacion: '2026-02-01',
    fechaInicioRelacion: '2026-02-01',
    modalidad: 'indeterminado',
    cargo: 'Ejecutivo Senior de Ventas y Cuentas Clave',
    clasificacion: 'ventas',
    descripcionFunciones: 'Comercialización de líneas de productos industriales, prospección de clientes corporativos en la región central, gestión de cobranza efectiva, visitas en campo y cumplimiento de cuotas de facturación.',
    lugarPrestacion: 'Región Capital y Central con sede operativa en Caracas',
    domicilioEspecialConvenido: 'Caracas, Circunscripción Judicial del Distrito Capital',
    tipoJornada: 'Diurna',
    horasSemanales: 40,
    horarioDetallado: 'Lunes a Viernes de 8:00 AM a 5:00 PM con 1 hora de descanso y almuerzo',
    diasDescanso: 'Sábados y Domingos continuos',
    empresaId: 'empresa-003',
    empresa: DEFAULT_COMPANIES[2],
    trabajador: {
      nombres: 'Carlos Eduardo',
      apellidos: 'Mendoza Guillén',
      cedula: 'V-19.512.634',
      nacionalidad: 'Venezolana',
      edad: 32,
      estadoCivil: 'Soltero(a)',
      profesionOficio: 'T.S.U. en Mercadotecnia y Ventas',
      direccionHabitacion: 'Av. Andrés Bello, Residencias Parque Ávila, Piso 4, La Candelaria, Caracas',
      telefono: '+58 412-5551928',
      correo: 'carlos.mendoza@manufacturasve.com'
    },
    remuneracion: {
      tipoMoneda: 'USD_INDEXADO',
      salarioBaseMensualUSD: 500,
      salarioBaseMensualVEF: 500 * CURRENT_DEFAULT_BCV_RATE,
      tasaBCV: CURRENT_DEFAULT_BCV_RATE,
      fechaTasaBCV: '2026-10-05',
      periodicidadPago: 'Quincenal',
      diaPago: 'los días 15 y último de cada mes',
      lugarPago: 'cuenta bancaria nómina',
      cestaticketUSD: LEGAL_CESTATICKET_USD,
      cestaticketVEF: LEGAL_CESTATICKET_USD * CURRENT_DEFAULT_BCV_RATE,
      esquemaMixto: true,
      porcentajeComisionVentas: 3.5,
      baseComisionDescripcion: 'sobre monto neto efectivamente cobrado (Sentencia TSJ 341 - carácter salarial)',
      diasBonoVacacional: 15,
      diasUtilidades: 30,
      bonosNoSalarialesDeclarados: 0,
      alertaRiesgoSalarizacion: false
    },
    aplicaConvencionColectiva: false,
    incluyePeriodoPrueba: true,
    diasPrueba: 90,
    lopcymat: {
      ...getDefaultLopcymatData('ventas'),
      horasCapacitacionTrimestralesCompletadas: 12
    },
    dobleEjemplarEmitido: true,
    constanciaEntregaFirmada: true,
    status: 'firmado_ambos',
    numeroProrroga: 0
  },
  {
    id: 'contract-003',
    codigoExpediente: 'NOM-2026-0003',
    fechaCreacion: '2026-03-01',
    fechaInicioRelacion: '2026-03-01',
    modalidad: 'determinado',
    fechaCulminacion: '2026-09-30',
    duracionMeses: 7,
    causalArt64: 'naturaleza_servicio',
    justificacionCausalArt64: 'Mantenimiento mayor y reconfiguración de líneas electromecánicas de manufactura industrial por expansión temporal de planta (Art. 64 lit. a LOTTT)',
    numeroProrroga: 1, // En 1ra prórroga (alerta preventiva de semáforo amarillo)
    cargo: 'Técnico Especialista de Mantenimiento Electromecánico',
    clasificacion: 'operativo',
    descripcionFunciones: 'Mantenimiento preventivo y correctivo de motores trifásicos, tableros PLC, bombas hidráulicas y sistemas neumáticos de la línea de ensamblaje.',
    lugarPrestacion: 'Planta Industrial Guatire, Zona Industrial El Marqués, Edo. Miranda',
    domicilioEspecialConvenido: 'Guatire, Circunscripción Judicial del Estado Miranda',
    tipoJornada: 'Diurna',
    horasSemanales: 40,
    horarioDetallado: 'Lunes a Viernes de 7:30 AM a 4:30 PM con 1 hora de descanso y comida',
    diasDescanso: 'Sábados y Domingos continuos',
    empresaId: 'empresa-001',
    empresa: DEFAULT_COMPANIES[0],
    trabajador: {
      nombres: 'José Gregorio',
      apellidos: 'Pernía Castillo',
      cedula: 'V-20.104.992',
      nacionalidad: 'Venezolana',
      edad: 29,
      estadoCivil: 'Unión Estable de Hecho',
      profesionOficio: 'Técnico Medio Industrial Electromecánico',
      direccionHabitacion: 'Sector Castillejo, Manzana 12, Casa 45, Guatire, Estado Miranda',
      telefono: '+58 424-1928374',
      correo: 'jose.pernia@gmail.com'
    },
    remuneracion: {
      tipoMoneda: 'USD_INDEXADO',
      salarioBaseMensualUSD: 450,
      salarioBaseMensualVEF: 450 * CURRENT_DEFAULT_BCV_RATE,
      tasaBCV: CURRENT_DEFAULT_BCV_RATE,
      fechaTasaBCV: '2026-10-05',
      periodicidadPago: 'Quincenal',
      diaPago: 'los días 15 y último de cada mes',
      lugarPago: 'depósito nómina bancario',
      cestaticketUSD: LEGAL_CESTATICKET_USD,
      cestaticketVEF: LEGAL_CESTATICKET_USD * CURRENT_DEFAULT_BCV_RATE,
      esquemaMixto: false,
      diasBonoVacacional: 15,
      diasUtilidades: 30,
      bonosNoSalarialesDeclarados: 0,
      alertaRiesgoSalarizacion: false
    },
    aplicaConvencionColectiva: false,
    incluyePeriodoPrueba: false,
    lopcymat: {
      ...getDefaultLopcymatData('operativo'),
      horasCapacitacionTrimestralesCompletadas: 16
    },
    dobleEjemplarEmitido: true,
    constanciaEntregaFirmada: true,
    status: 'firmado_ambos'
  },
  {
    id: 'contract-004',
    codigoExpediente: 'NOM-2026-0004',
    fechaCreacion: '2026-09-20',
    fechaInicioRelacion: '2026-10-01',
    modalidad: 'indeterminado',
    cargo: 'Analista de Gestión Humana y Nómina',
    clasificacion: 'administrativo',
    descripcionFunciones: 'Cálculo de nóminas quincenales, liquidación de Cestaticket, control de aportes parafiscales (IVSS, INCES, BANAVIH), gestión de expedientes LOTTT y notificaciones LOPCYMAT.',
    lugarPrestacion: 'Sede Principal Chacao, Caracas',
    domicilioEspecialConvenido: 'Caracas, Distrito Capital',
    tipoJornada: 'Diurna',
    horasSemanales: 40,
    horarioDetallado: 'Lunes a Viernes de 8:30 AM a 5:00 PM con 1 hora de descanso',
    diasDescanso: 'Sábados y Domingos continuos',
    empresaId: 'empresa-004',
    empresa: DEFAULT_COMPANIES[3],
    trabajador: {
      nombres: 'Daniela Patricia',
      apellidos: 'Colmenares Urdaneta',
      cedula: 'V-22.654.123',
      nacionalidad: 'Venezolana',
      edad: 26,
      estadoCivil: 'Soltero(a)',
      profesionOficio: 'Licenciada en Relaciones Industriales (UCAB)',
      direccionHabitacion: 'Calle Sucre con Boyacá, Edf. Doña María, San Bernardino, Caracas',
      telefono: '+58 416-9871234',
      correo: 'daniela.colmenares@gmail.com'
    },
    remuneracion: {
      tipoMoneda: 'USD_INDEXADO',
      salarioBaseMensualUSD: 600,
      salarioBaseMensualVEF: 600 * CURRENT_DEFAULT_BCV_RATE,
      tasaBCV: CURRENT_DEFAULT_BCV_RATE,
      fechaTasaBCV: '2026-10-05',
      periodicidadPago: 'Quincenal',
      diaPago: 'los días 15 y último de cada mes',
      lugarPago: 'cuenta nómina',
      cestaticketUSD: LEGAL_CESTATICKET_USD,
      cestaticketVEF: LEGAL_CESTATICKET_USD * CURRENT_DEFAULT_BCV_RATE,
      esquemaMixto: false,
      diasBonoVacacional: 15,
      diasUtilidades: 30,
      bonosNoSalarialesDeclarados: 0,
      alertaRiesgoSalarizacion: false
    },
    aplicaConvencionColectiva: false,
    incluyePeriodoPrueba: true,
    diasPrueba: 90,
    lopcymat: {
      ...getDefaultLopcymatData('administrativo'),
      horasCapacitacionTrimestralesCompletadas: 4
    },
    dobleEjemplarEmitido: false,
    constanciaEntregaFirmada: false,
    status: 'pendiente_firma',
    numeroProrroga: 0
  },
  {
    id: 'contract-005',
    codigoExpediente: 'NOM-2026-0005',
    fechaCreacion: '2026-10-02',
    fechaInicioRelacion: '2026-10-02',
    modalidad: 'indeterminado',
    cargo: 'Técnico Operador / Cauchero y Mecánico Ligero',
    clasificacion: 'unidad_obra',
    descripcionFunciones: 'Montaje, desmontaje, reparación y balanceo de neumáticos, rotación, alineación y servicios de mantenimiento automotriz ligero (cambio de aceite, frenos, bujías y fluidos), operando las herramientas y maquinarias asignadas de conformidad con las instrucciones técnicas de LA ENTIDAD DE TRABAJO.',
    lugarPrestacion: 'Taller Central de Cauchos y Mecánica Rápida - Chacao, Miranda',
    domicilioEspecialConvenido: 'Caracas, Circunscripción Judicial del Distrito Capital y Estado Miranda',
    tipoJornada: 'Diurna',
    horasSemanales: 40,
    horarioDetallado: 'Lunes a Viernes de 8:00 AM a 5:00 PM con 1 hora de descanso para el almuerzo no imputable a la jornada',
    diasDescanso: 'Sábados y Domingos continuos',
    empresaId: 'empresa-002',
    empresa: DEFAULT_COMPANIES[1],
    trabajador: {
      nombres: 'Yorman José',
      apellidos: 'Rondón Parra',
      cedula: 'V-21.849.501',
      nacionalidad: 'Venezolana',
      edad: 31,
      estadoCivil: 'Soltero(a)',
      profesionOficio: 'Técnico Operador Cauchero y Mecánico Ligero',
      direccionHabitacion: 'Sector Carapita, Calle San José, Casa 18, Antímano, Caracas',
      telefono: '+58 412-8822991',
      correo: 'yorman.rondon@email.com'
    },
    remuneracion: {
      tipoMoneda: 'USD_INDEXADO',
      salarioBaseMensualUSD: 450,
      salarioBaseMensualVEF: 450 * CURRENT_DEFAULT_BCV_RATE,
      tasaBCV: CURRENT_DEFAULT_BCV_RATE,
      fechaTasaBCV: '2026-10-05',
      periodicidadPago: 'Quincenal',
      diaPago: 'los días 15 y último de cada mes',
      lugarPago: 'transferencia bancaria a cuenta nómina del TRABAJADOR con relación de servicios',
      cestaticketUSD: LEGAL_CESTATICKET_USD,
      cestaticketVEF: LEGAL_CESTATICKET_USD * CURRENT_DEFAULT_BCV_RATE,
      esquemaMixto: false,
      esUnidadDeObra: true,
      garantiaSalarioMinimoArt115: true,
      tarifasComisionUnidadObra: [
        { servicio: 'Montaje, desmontaje y balanceo de neumático', porcentajeOMonto: '25% mano de obra facturada' },
        { servicio: 'Reparación de pinchazos y colocación de parches en caliente/frío', porcentajeOMonto: '30% mano de obra facturada' },
        { servicio: 'Alineación de dirección y balanceo computarizado', porcentajeOMonto: '25% mano de obra facturada' },
        { servicio: 'Mecánica ligera preventiva (cambio de aceite, filtros, frenos, fluidos)', porcentajeOMonto: '25% mano de obra facturada' }
      ],
      diasBonoVacacional: 15,
      diasUtilidades: 30,
      bonosNoSalarialesDeclarados: 0,
      alertaRiesgoSalarizacion: false
    },
    aplicaConvencionColectiva: false,
    incluyePeriodoPrueba: true,
    diasPrueba: 90,
    lopcymat: {
      ...getDefaultLopcymatData('unidad_obra'),
      horasCapacitacionTrimestralesCompletadas: 16
    },
    dobleEjemplarEmitido: true,
    constanciaEntregaFirmada: true,
    status: 'firmado_ambos',
    numeroProrroga: 0
  }
];
